apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP # because there are multiple subtype of service
  selector:
    component: web
  ports:
    - port: 3000
      targetPort: 3000
